import useTitle from "../CustomHooks/useTitle";

const Blogs = () => {
    useTitle('PlayfulRides | Blogs')
    return (
        <div className="container mx-auto mt-4">
            <h2 className="text-gray-500 text-4xl text-center font-bold mb-3">Blogs</h2>
            <ul>
                <li className="border-2 border-gray-200 py-4 rounded-8 mb-3 px-3">
                    
                        <h3 className="text-lg font-semibold">
                            What is an access token and refresh token?
                        </h3>
                        <p>
                            Access tokens and refresh tokens are two types of tokens that are used in OAuth 2.0 authorization. An access token is a short-lived token that is used to access protected resources. A refresh token is a long-lived token that can be used to obtain new access tokens.
                            <br />
                            Access tokens are typically generated by the authorization server when a user authenticates with a client application. The access token is then sent to the client application, which can use it to access protected resources.
                            <br />
                            Refresh tokens are also generated by the authorization server when a user authenticates with a client application. It can take more time for refresh token to be expired. The client application can use the refresh token to obtain a new access token if  the current access token expires.
                        </p>
                    
                </li>
                <li className="border-2 border-gray-200 py-4 rounded-8 mb-3 px-3">
                    
                        <h3 className="text-lg font-semibold">
                            Compare SQL and NoSQL databases
                        </h3>
                        <p>
                            SQL databases stores data in row and column format, where each row is a record and columns are piece of data. SQL databases use queries to access data. Queries are written in a language called SQL.
                            <br />
                            NoSQL databases store data in different ways, depending on the type of NoSQL database. NoSQL data stored as document in some database, while in other database can be stored as key and value pairs. NoSQL databases have different methods to access data, depending on the type of NoSQL database.
                        </p>
                    
                </li>
                <li className="border-2 border-gray-200 py-4 rounded-8 mb-3 px-3">
                    
                        <h3 className="text-lg font-semibold">
                            What is Express JS? What is Nest JS
                        </h3>
                        <p>
                            Express JS is a web application framework for Node.js. It is a popular framework for building web applications and APIs. Express JS is open source and free to use.
                            <br></br>
                            Nest JS is a framework built on top of Express JS. It provides a number of features that make it easier to build complex web applications and APIs. Nest JS is also open source and free to use.
                        </p>
                    
                </li>
                <li className="border-2 border-gray-200 py-4 rounded-8 mb-3 px-3">
                    
                        <h3 className="text-lg font-semibold">
                            What is MongoDB aggregate and how does it work?
                        </h3>
                        <p>
                            MongoDB aggregate is a powerful tool that can be used to perform complex queries on MongoDB data. Aggregate queries are written in a language called aggregation pipeline. The aggregation pipeline consists of a series of stages that are applied to the data in sequence. Each stage performs a specific operation on the data.
                            <br></br>
                            The aggregation pipeline can be used to perform a variety of tasks, such as grouping data, calculating aggregates, and filtering data. The aggregation pipeline is a powerful tool that can be used to simplify complex queries and to extract insights from MongoDB data.
                        </p>
                    
                </li>
            </ul>
        </div>
    );
};

export default Blogs;